# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Mon Mar 11 20:00:12 2024 from "C:\DriveD\MyPro\DataProc\Parser_Script\Python\+media\+voice\pjMusicRepeater\forms_.wxg"
#

import wx




class _692159013_wxToolBar(wx.ToolBar):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.TB_3DBUTTONS | wx.TB_TEXT
        wx.ToolBar.__init__(self, *args, **kwds)
        self.AddTool(wx.NewId(), "Cut", wx.ArtProvider.GetBitmap(wx.ART_CUT, wx.ART_TOOLBAR, (24, 24)), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.AddTool(wx.NewId(), "Go dir up", wx.ArtProvider.GetBitmap(wx.ART_GO_DIR_UP, wx.ART_TOOLBAR, (24, 24)), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.Realize()

